-- phpMyAdmin SQL Dump
-- version 4.7.9
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Waktu pembuatan: 27 Jan 2020 pada 01.13
-- Versi server: 10.1.31-MariaDB
-- Versi PHP: 7.2.3

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `sekolah`
--

-- --------------------------------------------------------

--
-- Struktur dari tabel `rapor_pribadi`
--

CREATE TABLE `rapor_pribadi` (
  `id_rapor` int(5) NOT NULL,
  `nis` varchar(20) NOT NULL,
  `nama` varchar(50) NOT NULL,
  `kelas` varchar(15) NOT NULL,
  `sekolah` varchar(100) NOT NULL,
  `tahun_pelajaran` varchar(20) NOT NULL,
  `alamat` text NOT NULL,
  `sikap_spiritual` text NOT NULL,
  `sikap_sosial` text NOT NULL,
  `exs1_nama` varchar(30) NOT NULL,
  `exs1_nilai` varchar(100) NOT NULL,
  `exs1_predikat` text NOT NULL,
  `exs2_nama` varchar(30) NOT NULL,
  `exs2_nilai` varchar(100) NOT NULL,
  `exs2_predikat` text NOT NULL,
  `exs3_nama` varchar(30) NOT NULL,
  `exs3_nilai` varchar(100) NOT NULL,
  `exs3_predikat` text NOT NULL,
  `exs4_nama` varchar(30) NOT NULL,
  `exs4_nilai` varchar(100) NOT NULL,
  `exs4_predikat` text NOT NULL,
  `tinggi_badan1` varchar(100) NOT NULL,
  `tinggi_badan2` varchar(100) NOT NULL,
  `berat_badan1` varchar(100) NOT NULL,
  `berat_badan2` varchar(100) NOT NULL,
  `pendengaran` varchar(10) NOT NULL,
  `penglihatan` varchar(10) NOT NULL,
  `gigi` varchar(10) NOT NULL,
  `prestasi1_jenis` varchar(50) NOT NULL,
  `prestasi1_keterangan` varchar(50) NOT NULL,
  `prestasi2_jenis` varchar(50) NOT NULL,
  `prestasi2_keterangan` varchar(50) NOT NULL,
  `prestasi3_jenis` varchar(50) NOT NULL,
  `prestasi3_keterangan` varchar(50) NOT NULL,
  `prestasi1_tgl` text NOT NULL,
  `prestasi2_tgl` text NOT NULL,
  `prestasi3_tgl` text NOT NULL,
  `sakit` varchar(50) NOT NULL,
  `izin` varchar(50) NOT NULL,
  `alpa` varchar(50) NOT NULL,
  `saran` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data untuk tabel `rapor_pribadi`
--

INSERT INTO `rapor_pribadi` (`id_rapor`, `nis`, `nama`, `kelas`, `sekolah`, `tahun_pelajaran`, `alamat`, `sikap_spiritual`, `sikap_sosial`, `exs1_nama`, `exs1_nilai`, `exs1_predikat`, `exs2_nama`, `exs2_nilai`, `exs2_predikat`, `exs3_nama`, `exs3_nilai`, `exs3_predikat`, `exs4_nama`, `exs4_nilai`, `exs4_predikat`, `tinggi_badan1`, `tinggi_badan2`, `berat_badan1`, `berat_badan2`, `pendengaran`, `penglihatan`, `gigi`, `prestasi1_jenis`, `prestasi1_keterangan`, `prestasi2_jenis`, `prestasi2_keterangan`, `prestasi3_jenis`, `prestasi3_keterangan`, `prestasi1_tgl`, `prestasi2_tgl`, `prestasi3_tgl`, `sakit`, `izin`, `alpa`, `saran`) VALUES
(81, '1099', 'Arka Ra\'if Hamdani', 'kelas 1', 'SDN 2 Glagah Temon Kulon Progo', '2017 / 2018', 'Glagah, Glagah, Temon, Kulon Progo', 'Sangat baik dalam   ketaatan beribadah, berdoa sebelum dan sesudah melakukan kegiatan, Baik dalam perilaku bersyukur, toleransi dalam beribadah, ', 'Baik dalam sikap jujur, disiplin, percaya diri, tanggung jawab, sopan santun, kerja sama, ', 'Pramuka', 'B', 'Sudah mampu dalam membaca syahadat, baik dalam membaca doa sehari-hari, memberi salam pramuka dan mengenal dwi satya dan dwi darma', 'TPA', 'B', 'Sudah baik dalam membaca surat-suratan pendek (Al-Fatihah, Al-Ikhlas,  An-Naas, Al-Falah), mampu membaca doa sehari-hari (doa sebelum makan, sebelum tidur, sebelum wudlu)', '', '', '', '', '', '', '103', '', '15', '', 'baik', 'baik', 'baik', '-', '-', '-', '-', '-', '-', '', '', '', '', '', '', 'Tingkatkan belajar membaca !'),
(82, '1100', 'Athaya Alifia Maulida Azahra', 'kelas 1', 'SDN 2 Glagah Temon Kulon Progo', '2017 / 2018', 'Bebekan, Glagah, Temon, Kulon Progo', 'Baik dalam ketaatan beribadah, perilaku bersyukur, berdoa sebelum dan sesudah melakukan kegiatan, toleransi dalam beribadah, ', 'Baik dalam sikap jujur, disiplin, percaya diri, tanggung jawab, sopan santun, kerja sama, ', 'Pramuka', 'B', 'Sudah mampu dalam membaca syahadat, baik dalam membaca doa sehari-hari, memberi salam pramuka dan mengenal dwi satya dan dwi darma', 'TPA', 'B', 'Sudah baik dalam membaca surat-suratan pendek (Al-Fatihah, Al-Ikhlas,  An-Naas, Al-Falah), mampu membaca doa sehari-hari (doa sebelum makan, sebelum tidur, sebelum wudlu)', '', '', '', '', '', '', '102', '', '21', '', 'baik', 'baik', 'baik', '-', '-', '-', '-', '-', '-', '', '', '', '', '', '', 'Belajarlah yang lebih giat lagi, perbanyak belajar menghitung !'),
(83, '1101', 'Danar Neva Patrias', 'kelas 1', 'SDN 2 Glagah Temon Kulon Progo', '2017 / 2018', 'Sangkretan, Glagah, Temon, Kulon Progo', 'Sangat baik dalam   ketaatan beribadah, perilaku bersyukur, berdoa sebelum dan sesudah melakukan kegiatan, toleransi dalam beribadah, ', 'Baik dalam sikap jujur, disiplin, percaya diri, tanggung jawab, sopan santun, kerja sama, ', 'Pramuka', 'B', 'Sudah mampu dalam membaca syahadat, baik dalam membaca doa sehari-hari, memberi salam pramuka dan mengenal dwi satya dan dwi darma', 'TPA', 'B', 'Sudah baik dalam membaca surat-suratan pendek (Al-Fatihah, Al-Ikhlas,  An-Naas, Al-Falah), mampu membaca doa sehari-hari (doa sebelum makan, sebelum tidur, sebelum wudlu)', '', '', '', '', '', '', '119', '', '25', '', 'baik', 'baik', 'baik', '-', '-', '-', '-', '-', '-', '', '', '', '', '', '', 'Belajarlah yang lebih giat lagi, perbanyak latihan menulis !'),
(84, '1102', 'Davila Rebiyansa Putra', 'kelas 1', 'SDN 2 Glagah Temon Kulon Progo', '2017 / 2018', 'Glagah, Glagah, Temon, Kulon Progo', 'Baik dalam ketaatan beribadah, perilaku bersyukur, berdoa sebelum dan sesudah melakukan kegiatan, toleransi dalam beribadah, ', 'Baik dalam sikap jujur, disiplin, percaya diri, tanggung jawab, sopan santun, kerja sama, ', 'Pramuka', 'B', 'Sudah mampu dalam membaca syahadat, baik dalam membaca doa sehari-hari, memberi salam pramuka dan mengenal dwi satya dan dwi darma', 'TPA', 'B', 'Sudah baik dalam membaca surat-suratan pendek (Al-Fatihah, Al-Ikhlas,  An-Naas, Al-Falah), mampu membaca doa sehari-hari (doa sebelum makan, sebelum tidur, sebelum wudlu)', '', '', '', '', '', '', '125', '', '21', '', 'baik', 'baik', 'baik', '-', '-', '-', '-', '-', '-', '', '', '', '', '', '', 'Tingkatkan belajarmu !'),
(85, '1103', 'Dyaz Eka Winata', 'kelas 1', 'SDN 2 Glagah Temon Kulon Progo', '2017 / 2018', 'Logede, Glagah, Temon, Kulon Progo', 'Sangat baik dalam   ketaatan beribadah, perilaku bersyukur, Baik dalam berdoa sebelum dan sesudah melakukan kegiatan, toleransi dalam beribadah, ', 'Baik dalam sikap jujur, disiplin, percaya diri, tanggung jawab, sopan santun, kerja sama, ', 'Pramuka', 'B', 'Sudah mampu dalam membaca syahadat, baik dalam membaca doa sehari-hari, memberi salam pramuka dan mengenal dwi satya dan dwi darma', 'TPA', 'B', 'Sudah baik dalam membaca surat-suratan pendek (Al-Fatihah, Al-Ikhlas,  An-Naas, Al-Falah), mampu membaca doa sehari-hari (doa sebelum makan, sebelum tidur, sebelum wudlu)', '', '', '', '', '', '', '121', '', '22', '', 'baik', 'baik', 'baik', '-', '-', '-', '-', '-', '-', '', '', '', '', '', '', 'Belajarlah yang lebih giat lagi, perbanyak belajar menghitung !'),
(86, '1104', 'Dzaky Athaya Muhammad Salim', 'kelas 1', 'SDN 2 Glagah Temon Kulon Progo', '2017 / 2018', 'Keboan, Karangwuni, Wates, Kulon Progo', 'Baik dalam ketaatan beribadah, perilaku bersyukur, berdoa sebelum dan sesudah melakukan kegiatan, toleransi dalam beribadah, ', 'Baik dalam sikap jujur, disiplin, percaya diri, tanggung jawab, sopan santun, kerja sama, ', 'Pramuka', 'B', 'Sudah mampu dalam membaca syahadat, baik dalam membaca doa sehari-hari, memberi salam pramuka dan mengenal dwi satya dan dwi darma', 'TPA', 'B', 'Sudah baik dalam membaca surat-suratan pendek (Al-Fatihah, Al-Ikhlas,  An-Naas, Al-Falah), mampu membaca doa sehari-hari (doa sebelum makan, sebelum tidur, sebelum wudlu)', '', '', '', '', '', '', '120', '', '23', '', 'kurang bai', 'baik', 'baik', '-', '-', '-', '-', '-', '-', '', '', '', '', '', '', 'Belajarlah yang lebih giat, tingkatkan kedisiplinan !'),
(87, '1105', 'Haya Hafizhah', 'kelas 1', 'SDN 2 Glagah Temon Kulon Progo', '2017 / 2018', 'Glagah, Glagah, Temon, Kulon Progo', 'Sangat baik dalam   ketaatan beribadah, perilaku bersyukur, berdoa sebelum dan sesudah melakukan kegiatan, Baik dalam toleransi dalam beribadah, ', 'Sangat  sopan santun, kerja sama, Baik dalam sikap jujur, disiplin, percaya diri, tanggung jawab, ', 'Pramuka', 'B', 'Sudah mampu dalam membaca syahadat, baik dalam membaca doa sehari-hari, memberi salam pramuka dan mengenal dwi satya dan dwi darma', 'TPA', 'B', 'Sudah baik dalam membaca surat-suratan pendek (Al-Fatihah, Al-Ikhlas,  An-Naas, Al-Falah), mampu membaca doa sehari-hari (doa sebelum makan, sebelum tidur, sebelum wudlu)', '', '', '', '', '', '', '115', '', '19', '', 'baik', 'baik', 'baik', '-', '-', '-', '-', '-', '-', '', '', '', '', '', '', 'Belajarlah yang lebih giat lagi !'),
(88, '1106', 'Kevin Aldi Prasetya', 'kelas 1', 'SDN 2 Glagah Temon Kulon Progo', '2017 / 2018', 'Glagah, Glagah, Temon, Kulon Progo', 'Baik dalam ketaatan beribadah, perilaku bersyukur, berdoa sebelum dan sesudah melakukan kegiatan, toleransi dalam beribadah, ', 'Baik dalam sikap jujur, disiplin, percaya diri, tanggung jawab, sopan santun, kerja sama, ', 'Pramuka', 'B', 'Sudah mampu dalam membaca syahadat, baik dalam membaca doa sehari-hari, memberi salam pramuka dan mengenal dwi satya dan dwi darma', 'TPA', 'B', 'Sudah baik dalam membaca surat-suratan pendek (Al-Fatihah, Al-Ikhlas,  An-Naas, Al-Falah), mampu membaca doa sehari-hari (doa sebelum makan, sebelum tidur, sebelum wudlu)', '', '', '', '', '', '', '113', '', '25', '', 'kurang bai', 'baik', 'baik', '-', '-', '-', '-', '-', '-', '', '', '', '', '', '', 'Tingkatkan belajarmu, perbanyak belajar menulis !'),
(89, '1107', 'Miswa Putri Ramadhani', 'kelas 1', 'SDN 2 Glagah Temon Kulon Progo', '2017 / 2018', 'Sangkretan, Glagah, Temon, Kulon Progo', 'Sangat baik dalam   ketaatan beribadah, berdoa sebelum dan sesudah melakukan kegiatan, Baik dalam perilaku bersyukur, toleransi dalam beribadah, ', 'Sangat  sopan santun, Baik dalam sikap jujur, disiplin, percaya diri, tanggung jawab, kerja sama, ', 'Pramuka', 'B', 'Sudah mampu dalam membaca syahadat, baik dalam membaca doa sehari-hari, memberi salam pramuka dan mengenal dwi satya dan dwi darma', 'TPA', 'B', 'Sudah baik dalam membaca surat-suratan pendek (Al-Fatihah, Al-Ikhlas,  An-Naas, Al-Falah), mampu membaca doa sehari-hari (doa sebelum makan, sebelum tidur, sebelum wudlu)', '', '', '', '', '', '', '117', '', '19', '', 'baik', 'baik', 'baik', '-', '-', '-', '-', '-', '-', '', '', '', '', '', '', 'Belajarlah yang lebih giat lagi !'),
(90, '1108', 'Muhammad Rafi Aldiansyah', 'kelas 1', 'SDN 2 Glagah Temon Kulon Progo', '2017 / 2018', 'Bebekan, Glagah, Temon, Kulon Progo', 'Sangat baik dalam   ketaatan beribadah, perilaku bersyukur, berdoa sebelum dan sesudah melakukan kegiatan, Baik dalam toleransi dalam beribadah, ', 'Baik dalam sikap jujur, disiplin, percaya diri, tanggung jawab, sopan santun, kerja sama, ', 'Pramuka', 'B', 'Sudah mampu dalam membaca syahadat, baik dalam membaca doa sehari-hari, memberi salam pramuka dan mengenal dwi satya dan dwi darma', 'TPA', 'B', 'Sudah baik dalam membaca surat-suratan pendek (Al-Fatihah, Al-Ikhlas,  An-Naas, Al-Falah), mampu membaca doa sehari-hari (doa sebelum makan, sebelum tidur, sebelum wudlu)', '', '', '', '', '', '', '120', '', '18', '', 'baik', 'kurang bai', 'baik', '-', '-', '-', '-', '-', '-', '', '', '', '', '', '', 'Belajarlah yang lebih giat lagi !'),
(91, '1109', 'Nabila Ayu Saskia Ningrum', 'kelas 1', 'SDN 2 Glagah Temon Kulon Progo', '2017 / 2018', 'Bebekan, Glagah, Temon, Kulon Progo', 'Baik dalam ketaatan beribadah, cukup dalam perilaku bersyukur, berdoa sebelum dan sesudah melakukan kegiatan, toleransi dalam beribadah, ', 'Baik dalam sikap jujur, disiplin, percaya diri, tanggung jawab, sopan santun, kerja sama, ', 'Pramuka', 'B', 'Sudah mampu dalam membaca syahadat, baik dalam membaca doa sehari-hari, memberi salam pramuka dan mengenal dwi satya dan dwi darma', 'TPA', 'B', 'Sudah baik dalam membaca surat-suratan pendek (Al-Fatihah, Al-Ikhlas,  An-Naas, Al-Falah), mampu membaca doa sehari-hari (doa sebelum makan, sebelum tidur, sebelum wudlu)', '', '', '', '', '', '', '117', '', '22', '', 'baik', 'baik', 'baik', '-', '-', '-', '-', '-', '-', '', '', '', '', '', '', 'Tingkatkan belajarmu, perbanyak belajar membaca dan menulis !'),
(92, '1110', 'Nabila Septianing Tyas', 'kelas 1', 'SDN 2 Glagah Temon Kulon Progo', '2017 / 2018', 'Glagah, Glagah, Temon, Kulon Progo', 'Sangat baik dalam   berdoa sebelum dan sesudah melakukan kegiatan, Baik dalam ketaatan beribadah, perilaku bersyukur, toleransi dalam beribadah, ', 'Baik dalam sikap jujur, disiplin, percaya diri, tanggung jawab, sopan santun, kerja sama, ', 'Pramuka', 'B', 'Sudah mampu dalam membaca syahadat, baik dalam membaca doa sehari-hari, memberi salam pramuka dan mengenal dwi satya dan dwi darma', 'TPA', 'B', 'Sudah baik dalam membaca surat-suratan pendek (Al-Fatihah, Al-Ikhlas,  An-Naas, Al-Falah), mampu membaca doa sehari-hari (doa sebelum makan, sebelum tidur, sebelum wudlu)', '', '', '', '', '', '', '138', '', '42', '', 'baik', 'baik', 'baik', '-', '-', '-', '-', '-', '-', '', '', '', '', '', '', 'Belajarlah yang lebih giat lagi !'),
(93, '1111', 'Rakha Boma Nandana', 'kelas 1', 'SDN 2 Glagah Temon Kulon Progo', '2017 / 2018', 'Glagah, Glagah, Temon, Kulon Progo', 'Sangat baik dalam   ketaatan beribadah, Baik dalam perilaku bersyukur, berdoa sebelum dan sesudah melakukan kegiatan, toleransi dalam beribadah, ', 'Baik dalam sikap jujur, disiplin, percaya diri, tanggung jawab, sopan santun, kerja sama, ', 'Pramuka', 'B', 'Sudah mampu dalam membaca syahadat, baik dalam membaca doa sehari-hari, memberi salam pramuka dan mengenal dwi satya dan dwi darma', 'TPA', 'B', 'Sudah baik dalam membaca surat-suratan pendek (Al-Fatihah, Al-Ikhlas,  An-Naas, Al-Falah), mampu membaca doa sehari-hari (doa sebelum makan, sebelum tidur, sebelum wudlu)', '', '', '', '', '', '', '117', '', '19', '', 'baik', 'baik', 'baik', '-', '-', '-', '-', '-', '-', '', '', '', '', '', '', 'Tingkatkan belajar membaca !'),
(94, '1112', 'Rayyan Khairul Azam', 'kelas 1', 'SDN 2 Glagah Temon Kulon Progo', '2017 / 2018', 'Sangkretan, Glagah, Temon, Kulon Progo', 'Sangat baik dalam   ketaatan beribadah, perilaku bersyukur, berdoa sebelum dan sesudah melakukan kegiatan, Baik dalam toleransi dalam beribadah, ', 'Baik dalam sikap jujur, disiplin, percaya diri, tanggung jawab, sopan santun, kerja sama, ', 'Pramuka', 'B', 'Sudah mampu dalam membaca syahadat, baik dalam membaca doa sehari-hari, memberi salam pramuka dan mengenal dwi satya dan dwi darma', 'TPA', 'B', 'Sudah baik dalam membaca surat-suratan pendek (Al-Fatihah, Al-Ikhlas,  An-Naas, Al-Falah), mampu membaca doa sehari-hari (doa sebelum makan, sebelum tidur, sebelum wudlu)', '', '', '', '', '', '', '121', '', '27', '', 'baik', 'baik', 'baik', '-', '-', '-', '-', '-', '-', '', '', '', '', '', '', 'Belajarlah yang lebih giat lagi !'),
(95, '1113', 'Regina Astitra Rahmadonna', 'kelas 1', 'SDN 2 Glagah Temon Kulon Progo', '2017 / 2018', 'Sangkretan, Glagah, Temon, Kulon Progo', 'Sangat baik dalam   ketaatan beribadah, perilaku bersyukur, berdoa sebelum dan sesudah melakukan kegiatan, Baik dalam toleransi dalam beribadah, ', 'Baik dalam sikap jujur, disiplin, percaya diri, tanggung jawab, sopan santun, kerja sama, ', 'Pramuka', 'B', 'Sudah mampu dalam membaca syahadat, baik dalam membaca doa sehari-hari, memberi salam pramuka dan mengenal dwi satya dan dwi darma', 'TPA', 'B', 'Sudah baik dalam membaca surat-suratan pendek (Al-Fatihah, Al-Ikhlas,  An-Naas, Al-Falah), mampu membaca doa sehari-hari (doa sebelum makan, sebelum tidur, sebelum wudlu)', '', '', '', '', '', '', '120', '', '17', '', 'baik', 'baik', 'baik', '-', '-', '-', '-', '-', '-', '', '', '', '', '', '', 'Belajarlah yang lebih giat lagi !'),
(96, '1114', 'Safiq Satriawan', 'kelas 1', 'SDN 2 Glagah Temon Kulon Progo', '2017 / 2018', 'Glagah, Glagah, Temon, Kulon Progo', 'Baik dalam ketaatan beribadah, perilaku bersyukur, berdoa sebelum dan sesudah melakukan kegiatan, toleransi dalam beribadah, ', 'Baik dalam sikap jujur, disiplin, percaya diri, tanggung jawab, sopan santun, kerja sama, ', 'Pramuka', 'B', 'Sudah mampu dalam membaca syahadat, baik dalam membaca doa sehari-hari, memberi salam pramuka dan mengenal dwi satya dan dwi darma', 'TPA', 'B', 'Sudah baik dalam membaca surat-suratan pendek (Al-Fatihah, Al-Ikhlas,  An-Naas, Al-Falah), mampu membaca doa sehari-hari (doa sebelum makan, sebelum tidur, sebelum wudlu)', '', '', '', '', '', '', '118', '', '15', '', 'baik', 'baik', 'baik', '-', '-', '-', '-', '-', '-', '', '', '', '', '', '', 'Belajarlah yang lebih giat, perbanyak belajar menulis !'),
(97, '1099', 'Arka Ra\'if Hamdani', 'kelas 3', 'SD Negeri 2 Glagah', 'Gasal 2017/2018', 'Glagah, Glagah, Temon, Kulon Progo', 'Sangat baik dalam   ketaatan beribadah, berdoa sebelum dan sesudah melakukan kegiatan, Baik dalam perilaku bersyukur, toleransi dalam beribadah, ', 'Baik dalam sikap jujur, disiplin, percaya diri, tanggung jawab, sopan santun, kerja sama, ', 'Pramuka', 'B', 'Sudah mampu dalam membaca syahadat, baik dalam membaca doa sehari-hari, memberi salam pramuka dan mengenal dwi satya dan dwi darma', 'TPA', 'B', 'Sudah baik dalam membaca surat-suratan pendek (Al-Fatihah, Al-Ikhlas,  An-Naas, Al-Falah), mampu membaca doa sehari-hari (doa sebelum makan, sebelum tidur, sebelum wudlu)', '', '', '', '', '', '', '103', '', '15', '', 'baik', 'baik', 'baik', '-', '-', '-', '-', '-', '-', '', '', '', '', '', '', 'Tingkatkan belajar membaca !'),
(98, '1100', 'Athaya Alifia Maulida Azahra', 'kelas 3', 'SD Negeri 2 Glagah', 'Gasal 2017/2018', 'Bebekan, Glagah, Temon, Kulon Progo', 'Baik dalam ketaatan beribadah, perilaku bersyukur, berdoa sebelum dan sesudah melakukan kegiatan, toleransi dalam beribadah, ', 'Baik dalam sikap jujur, disiplin, percaya diri, tanggung jawab, sopan santun, kerja sama, ', 'Pramuka', 'B', 'Sudah mampu dalam membaca syahadat, baik dalam membaca doa sehari-hari, memberi salam pramuka dan mengenal dwi satya dan dwi darma', 'TPA', 'B', 'Sudah baik dalam membaca surat-suratan pendek (Al-Fatihah, Al-Ikhlas,  An-Naas, Al-Falah), mampu membaca doa sehari-hari (doa sebelum makan, sebelum tidur, sebelum wudlu)', '', '', '', '', '', '', '102', '', '21', '', 'baik', 'baik', 'baik', '-', '-', '-', '-', '-', '-', '', '', '', '', '', '', 'Belajarlah yang lebih giat lagi, perbanyak belajar menghitung !'),
(99, '1101', 'Danar Neva Patrias', 'kelas 3', 'SD Negeri 2 Glagah', 'Gasal 2017/2018', 'Sangkretan, Glagah, Temon, Kulon Progo', 'Sangat baik dalam   ketaatan beribadah, perilaku bersyukur, berdoa sebelum dan sesudah melakukan kegiatan, toleransi dalam beribadah, ', 'Baik dalam sikap jujur, disiplin, percaya diri, tanggung jawab, sopan santun, kerja sama, ', 'Pramuka', 'B', 'Sudah mampu dalam membaca syahadat, baik dalam membaca doa sehari-hari, memberi salam pramuka dan mengenal dwi satya dan dwi darma', 'TPA', 'B', 'Sudah baik dalam membaca surat-suratan pendek (Al-Fatihah, Al-Ikhlas,  An-Naas, Al-Falah), mampu membaca doa sehari-hari (doa sebelum makan, sebelum tidur, sebelum wudlu)', '', '', '', '', '', '', '119', '', '25', '', 'baik', 'baik', 'baik', '-', '-', '-', '-', '-', '-', '', '', '', '', '', '', 'Belajarlah yang lebih giat lagi, perbanyak latihan menulis !'),
(100, '1102', 'Davila Rebiyansa Putra', 'kelas 3', 'SD Negeri 2 Glagah', 'Gasal 2017/2018', 'Glagah, Glagah, Temon, Kulon Progo', 'Baik dalam ketaatan beribadah, perilaku bersyukur, berdoa sebelum dan sesudah melakukan kegiatan, toleransi dalam beribadah, ', 'Baik dalam sikap jujur, disiplin, percaya diri, tanggung jawab, sopan santun, kerja sama, ', 'Pramuka', 'B', 'Sudah mampu dalam membaca syahadat, baik dalam membaca doa sehari-hari, memberi salam pramuka dan mengenal dwi satya dan dwi darma', 'TPA', 'B', 'Sudah baik dalam membaca surat-suratan pendek (Al-Fatihah, Al-Ikhlas,  An-Naas, Al-Falah), mampu membaca doa sehari-hari (doa sebelum makan, sebelum tidur, sebelum wudlu)', '', '', '', '', '', '', '125', '', '21', '', 'baik', 'baik', 'baik', '-', '-', '-', '-', '-', '-', '', '', '', '', '', '', 'Tingkatkan belajarmu !'),
(101, '1103', 'Dyaz Eka Winata', 'kelas 3', 'SD Negeri 2 Glagah', 'Gasal 2017/2018', 'Logede, Glagah, Temon, Kulon Progo', 'Sangat baik dalam   ketaatan beribadah, perilaku bersyukur, Baik dalam berdoa sebelum dan sesudah melakukan kegiatan, toleransi dalam beribadah, ', 'Baik dalam sikap jujur, disiplin, percaya diri, tanggung jawab, sopan santun, kerja sama, ', 'Pramuka', 'B', 'Sudah mampu dalam membaca syahadat, baik dalam membaca doa sehari-hari, memberi salam pramuka dan mengenal dwi satya dan dwi darma', 'TPA', 'B', 'Sudah baik dalam membaca surat-suratan pendek (Al-Fatihah, Al-Ikhlas,  An-Naas, Al-Falah), mampu membaca doa sehari-hari (doa sebelum makan, sebelum tidur, sebelum wudlu)', '', '', '', '', '', '', '121', '', '22', '', 'baik', 'baik', 'baik', '-', '-', '-', '-', '-', '-', '', '', '', '', '', '', 'Belajarlah yang lebih giat lagi, perbanyak belajar menghitung !'),
(102, '1104', 'Dzaky Athaya Muhammad Salim', 'kelas 3', 'SD Negeri 2 Glagah', 'Gasal 2017/2018', 'Keboan, Karangwuni, Wates, Kulon Progo', 'Baik dalam ketaatan beribadah, perilaku bersyukur, berdoa sebelum dan sesudah melakukan kegiatan, toleransi dalam beribadah, ', 'Baik dalam sikap jujur, disiplin, percaya diri, tanggung jawab, sopan santun, kerja sama, ', 'Pramuka', 'B', 'Sudah mampu dalam membaca syahadat, baik dalam membaca doa sehari-hari, memberi salam pramuka dan mengenal dwi satya dan dwi darma', 'TPA', 'B', 'Sudah baik dalam membaca surat-suratan pendek (Al-Fatihah, Al-Ikhlas,  An-Naas, Al-Falah), mampu membaca doa sehari-hari (doa sebelum makan, sebelum tidur, sebelum wudlu)', '', '', '', '', '', '', '120', '', '23', '', 'kurang bai', 'baik', 'baik', '-', '-', '-', '-', '-', '-', '', '', '', '', '', '', 'Belajarlah yang lebih giat, tingkatkan kedisiplinan !'),
(103, '1105', 'Haya Hafizhah', 'kelas 3', 'SD Negeri 2 Glagah', 'Gasal 2017/2018', 'Glagah, Glagah, Temon, Kulon Progo', 'Sangat baik dalam   ketaatan beribadah, perilaku bersyukur, berdoa sebelum dan sesudah melakukan kegiatan, Baik dalam toleransi dalam beribadah, ', 'Sangat  sopan santun, kerja sama, Baik dalam sikap jujur, disiplin, percaya diri, tanggung jawab, ', 'Pramuka', 'B', 'Sudah mampu dalam membaca syahadat, baik dalam membaca doa sehari-hari, memberi salam pramuka dan mengenal dwi satya dan dwi darma', 'TPA', 'B', 'Sudah baik dalam membaca surat-suratan pendek (Al-Fatihah, Al-Ikhlas,  An-Naas, Al-Falah), mampu membaca doa sehari-hari (doa sebelum makan, sebelum tidur, sebelum wudlu)', '', '', '', '', '', '', '115', '', '19', '', 'baik', 'baik', 'baik', '-', '-', '-', '-', '-', '-', '', '', '', '', '', '', 'Belajarlah yang lebih giat lagi !'),
(104, '1106', 'Kevin Aldi Prasetya', 'kelas 3', 'SD Negeri 2 Glagah', 'Gasal 2017/2018', 'Glagah, Glagah, Temon, Kulon Progo', 'Baik dalam ketaatan beribadah, perilaku bersyukur, berdoa sebelum dan sesudah melakukan kegiatan, toleransi dalam beribadah, ', 'Baik dalam sikap jujur, disiplin, percaya diri, tanggung jawab, sopan santun, kerja sama, ', 'Pramuka', 'B', 'Sudah mampu dalam membaca syahadat, baik dalam membaca doa sehari-hari, memberi salam pramuka dan mengenal dwi satya dan dwi darma', 'TPA', 'B', 'Sudah baik dalam membaca surat-suratan pendek (Al-Fatihah, Al-Ikhlas,  An-Naas, Al-Falah), mampu membaca doa sehari-hari (doa sebelum makan, sebelum tidur, sebelum wudlu)', '', '', '', '', '', '', '113', '', '25', '', 'kurang bai', 'baik', 'baik', '-', '-', '-', '-', '-', '-', '', '', '', '', '', '', 'Tingkatkan belajarmu, perbanyak belajar menulis !'),
(105, '1107', 'Miswa Putri Ramadhani', 'kelas 3', 'SD Negeri 2 Glagah', 'Gasal 2017/2018', 'Sangkretan, Glagah, Temon, Kulon Progo', 'Sangat baik dalam   ketaatan beribadah, berdoa sebelum dan sesudah melakukan kegiatan, Baik dalam perilaku bersyukur, toleransi dalam beribadah, ', 'Sangat  sopan santun, Baik dalam sikap jujur, disiplin, percaya diri, tanggung jawab, kerja sama, ', 'Pramuka', 'B', 'Sudah mampu dalam membaca syahadat, baik dalam membaca doa sehari-hari, memberi salam pramuka dan mengenal dwi satya dan dwi darma', 'TPA', 'B', 'Sudah baik dalam membaca surat-suratan pendek (Al-Fatihah, Al-Ikhlas,  An-Naas, Al-Falah), mampu membaca doa sehari-hari (doa sebelum makan, sebelum tidur, sebelum wudlu)', '', '', '', '', '', '', '117', '', '19', '', 'baik', 'baik', 'baik', '-', '-', '-', '-', '-', '-', '', '', '', '', '', '', 'Belajarlah yang lebih giat lagi !'),
(106, '1108', 'Muhammad Rafi Aldiansyah', 'kelas 3', 'SD Negeri 2 Glagah', 'Gasal 2017/2018', 'Bebekan, Glagah, Temon, Kulon Progo', 'Sangat baik dalam   ketaatan beribadah, perilaku bersyukur, berdoa sebelum dan sesudah melakukan kegiatan, Baik dalam toleransi dalam beribadah, ', 'Baik dalam sikap jujur, disiplin, percaya diri, tanggung jawab, sopan santun, kerja sama, ', 'Pramuka', 'B', 'Sudah mampu dalam membaca syahadat, baik dalam membaca doa sehari-hari, memberi salam pramuka dan mengenal dwi satya dan dwi darma', 'TPA', 'B', 'Sudah baik dalam membaca surat-suratan pendek (Al-Fatihah, Al-Ikhlas,  An-Naas, Al-Falah), mampu membaca doa sehari-hari (doa sebelum makan, sebelum tidur, sebelum wudlu)', '', '', '', '', '', '', '120', '', '18', '', 'baik', 'kurang bai', 'baik', '-', '-', '-', '-', '-', '-', '', '', '', '', '', '', 'Belajarlah yang lebih giat lagi !'),
(107, '1109', 'Nabila Ayu Saskia Ningrum', 'kelas 3', 'SD Negeri 2 Glagah', 'Gasal 2017/2018', 'Bebekan, Glagah, Temon, Kulon Progo', 'Baik dalam ketaatan beribadah, cukup dalam perilaku bersyukur, berdoa sebelum dan sesudah melakukan kegiatan, toleransi dalam beribadah, ', 'Baik dalam sikap jujur, disiplin, percaya diri, tanggung jawab, sopan santun, kerja sama, ', 'Pramuka', 'B', 'Sudah mampu dalam membaca syahadat, baik dalam membaca doa sehari-hari, memberi salam pramuka dan mengenal dwi satya dan dwi darma', 'TPA', 'B', 'Sudah baik dalam membaca surat-suratan pendek (Al-Fatihah, Al-Ikhlas,  An-Naas, Al-Falah), mampu membaca doa sehari-hari (doa sebelum makan, sebelum tidur, sebelum wudlu)', '', '', '', '', '', '', '117', '', '22', '', 'baik', 'baik', 'baik', '-', '-', '-', '-', '-', '-', '', '', '', '', '', '', 'Tingkatkan belajarmu, perbanyak belajar membaca dan menulis !'),
(108, '1110', 'Nabila Septianing Tyas', 'kelas 3', 'SD Negeri 2 Glagah', 'Gasal 2017/2018', 'Glagah, Glagah, Temon, Kulon Progo', 'Sangat baik dalam   berdoa sebelum dan sesudah melakukan kegiatan, Baik dalam ketaatan beribadah, perilaku bersyukur, toleransi dalam beribadah, ', 'Baik dalam sikap jujur, disiplin, percaya diri, tanggung jawab, sopan santun, kerja sama, ', 'Pramuka', 'B', 'Sudah mampu dalam membaca syahadat, baik dalam membaca doa sehari-hari, memberi salam pramuka dan mengenal dwi satya dan dwi darma', 'TPA', 'B', 'Sudah baik dalam membaca surat-suratan pendek (Al-Fatihah, Al-Ikhlas,  An-Naas, Al-Falah), mampu membaca doa sehari-hari (doa sebelum makan, sebelum tidur, sebelum wudlu)', '', '', '', '', '', '', '138', '', '42', '', 'baik', 'baik', 'baik', '-', '-', '-', '-', '-', '-', '', '', '', '', '', '', 'Belajarlah yang lebih giat lagi !'),
(109, '1111', 'Rakha Boma Nandana', 'kelas 3', 'SD Negeri 2 Glagah', 'Gasal 2017/2018', 'Glagah, Glagah, Temon, Kulon Progo', 'Sangat baik dalam   ketaatan beribadah, Baik dalam perilaku bersyukur, berdoa sebelum dan sesudah melakukan kegiatan, toleransi dalam beribadah, ', 'Baik dalam sikap jujur, disiplin, percaya diri, tanggung jawab, sopan santun, kerja sama, ', 'Pramuka', 'B', 'Sudah mampu dalam membaca syahadat, baik dalam membaca doa sehari-hari, memberi salam pramuka dan mengenal dwi satya dan dwi darma', 'TPA', 'B', 'Sudah baik dalam membaca surat-suratan pendek (Al-Fatihah, Al-Ikhlas,  An-Naas, Al-Falah), mampu membaca doa sehari-hari (doa sebelum makan, sebelum tidur, sebelum wudlu)', '', '', '', '', '', '', '117', '', '19', '', 'baik', 'baik', 'baik', '-', '-', '-', '-', '-', '-', '', '', '', '', '', '', 'Tingkatkan belajar membaca !'),
(110, '1112', 'Rayyan Khairul Azam', 'kelas 3', 'SD Negeri 2 Glagah', 'Gasal 2017/2018', 'Sangkretan, Glagah, Temon, Kulon Progo', 'Sangat baik dalam   ketaatan beribadah, perilaku bersyukur, berdoa sebelum dan sesudah melakukan kegiatan, Baik dalam toleransi dalam beribadah, ', 'Baik dalam sikap jujur, disiplin, percaya diri, tanggung jawab, sopan santun, kerja sama, ', 'Pramuka', 'B', 'Sudah mampu dalam membaca syahadat, baik dalam membaca doa sehari-hari, memberi salam pramuka dan mengenal dwi satya dan dwi darma', 'TPA', 'B', 'Sudah baik dalam membaca surat-suratan pendek (Al-Fatihah, Al-Ikhlas,  An-Naas, Al-Falah), mampu membaca doa sehari-hari (doa sebelum makan, sebelum tidur, sebelum wudlu)', '', '', '', '', '', '', '121', '', '27', '', 'baik', 'baik', 'baik', '-', '-', '-', '-', '-', '-', '', '', '', '', '', '', 'Belajarlah yang lebih giat lagi !'),
(111, '1113', 'Regina Astitra Rahmadonna', 'kelas 3', 'SD Negeri 2 Glagah', 'Gasal 2017/2018', 'Sangkretan, Glagah, Temon, Kulon Progo', 'Sangat baik dalam   ketaatan beribadah, perilaku bersyukur, berdoa sebelum dan sesudah melakukan kegiatan, Baik dalam toleransi dalam beribadah, ', 'Baik dalam sikap jujur, disiplin, percaya diri, tanggung jawab, sopan santun, kerja sama, ', 'Pramuka', 'B', 'Sudah mampu dalam membaca syahadat, baik dalam membaca doa sehari-hari, memberi salam pramuka dan mengenal dwi satya dan dwi darma', 'TPA', 'B', 'Sudah baik dalam membaca surat-suratan pendek (Al-Fatihah, Al-Ikhlas,  An-Naas, Al-Falah), mampu membaca doa sehari-hari (doa sebelum makan, sebelum tidur, sebelum wudlu)', '', '', '', '', '', '', '120', '', '17', '', 'baik', 'baik', 'baik', '-', '-', '-', '-', '-', '-', '', '', '', '', '', '', 'Belajarlah yang lebih giat lagi !'),
(112, '1114', 'Safiq Satriawan', 'kelas 3', 'SD Negeri 2 Glagah', 'Gasal 2017/2018', 'Glagah, Glagah, Temon, Kulon Progo', 'Baik dalam ketaatan beribadah, perilaku bersyukur, berdoa sebelum dan sesudah melakukan kegiatan, toleransi dalam beribadah, ', 'Baik dalam sikap jujur, disiplin, percaya diri, tanggung jawab, sopan santun, kerja sama, ', 'Pramuka', 'B', 'Sudah mampu dalam membaca syahadat, baik dalam membaca doa sehari-hari, memberi salam pramuka dan mengenal dwi satya dan dwi darma', 'TPA', 'B', 'Sudah baik dalam membaca surat-suratan pendek (Al-Fatihah, Al-Ikhlas,  An-Naas, Al-Falah), mampu membaca doa sehari-hari (doa sebelum makan, sebelum tidur, sebelum wudlu)', '', '', '', '', '', '', '118', '', '15', '', 'baik', 'baik', 'baik', '-', '-', '-', '-', '-', '-', '', '', '', '', '', '', 'Belajarlah yang lebih giat, perbanyak belajar menulis !'),
(113, '1099', 'Arka Ra\'if Hamdani', 'kelas 1', 'SD Negeri 2 Glagah', '', 'Glagah, Glagah, Temon, Kulon Progo', 'Sangat baik dalam   ketaatan beribadah, berdoa sebelum dan sesudah melakukan kegiatan, Baik dalam perilaku bersyukur, toleransi dalam beribadah, ', 'Baik dalam sikap jujur, disiplin, percaya diri, tanggung jawab, sopan santun, kerja sama, ', 'Pramuka', 'B', 'Sudah mampu dalam membaca syahadat, baik dalam membaca doa sehari-hari, memberi salam pramuka dan mengenal dwi satya dan dwi darma', 'TPA', 'B', 'Sudah baik dalam membaca surat-suratan pendek (Al-Fatihah, Al-Ikhlas,  An-Naas, Al-Falah), mampu membaca doa sehari-hari (doa sebelum makan, sebelum tidur, sebelum wudlu)', '', '', '', '', '', '', '103', '', '15', '', 'baik', 'baik', 'baik', '-', '-', '-', '-', '-', '-', '', '', '', '', '', '', 'Tingkatkan belajar membaca !'),
(114, '1100', 'Athaya Alifia Maulida Azahra', 'kelas 1', 'SD Negeri 2 Glagah', '', 'Bebekan, Glagah, Temon, Kulon Progo', 'Baik dalam ketaatan beribadah, perilaku bersyukur, berdoa sebelum dan sesudah melakukan kegiatan, toleransi dalam beribadah, ', 'Baik dalam sikap jujur, disiplin, percaya diri, tanggung jawab, sopan santun, kerja sama, ', 'Pramuka', 'B', 'Sudah mampu dalam membaca syahadat, baik dalam membaca doa sehari-hari, memberi salam pramuka dan mengenal dwi satya dan dwi darma', 'TPA', 'B', 'Sudah baik dalam membaca surat-suratan pendek (Al-Fatihah, Al-Ikhlas,  An-Naas, Al-Falah), mampu membaca doa sehari-hari (doa sebelum makan, sebelum tidur, sebelum wudlu)', '', '', '', '', '', '', '102', '', '21', '', 'baik', 'baik', 'baik', '-', '-', '-', '-', '-', '-', '', '', '', '', '', '', 'Belajarlah yang lebih giat lagi, perbanyak belajar menghitung !'),
(115, '1101', 'Danar Neva Patrias', 'kelas 1', 'SD Negeri 2 Glagah', '', 'Sangkretan, Glagah, Temon, Kulon Progo', 'Sangat baik dalam   ketaatan beribadah, perilaku bersyukur, berdoa sebelum dan sesudah melakukan kegiatan, toleransi dalam beribadah, ', 'Baik dalam sikap jujur, disiplin, percaya diri, tanggung jawab, sopan santun, kerja sama, ', 'Pramuka', 'B', 'Sudah mampu dalam membaca syahadat, baik dalam membaca doa sehari-hari, memberi salam pramuka dan mengenal dwi satya dan dwi darma', 'TPA', 'B', 'Sudah baik dalam membaca surat-suratan pendek (Al-Fatihah, Al-Ikhlas,  An-Naas, Al-Falah), mampu membaca doa sehari-hari (doa sebelum makan, sebelum tidur, sebelum wudlu)', '', '', '', '', '', '', '119', '', '25', '', 'baik', 'baik', 'baik', '-', '-', '-', '-', '-', '-', '', '', '', '', '', '', 'Belajarlah yang lebih giat lagi, perbanyak latihan menulis !'),
(116, '1102', 'Davila Rebiyansa Putra', 'kelas 1', 'SD Negeri 2 Glagah', '', 'Glagah, Glagah, Temon, Kulon Progo', 'Baik dalam ketaatan beribadah, perilaku bersyukur, berdoa sebelum dan sesudah melakukan kegiatan, toleransi dalam beribadah, ', 'Baik dalam sikap jujur, disiplin, percaya diri, tanggung jawab, sopan santun, kerja sama, ', 'Pramuka', 'B', 'Sudah mampu dalam membaca syahadat, baik dalam membaca doa sehari-hari, memberi salam pramuka dan mengenal dwi satya dan dwi darma', 'TPA', 'B', 'Sudah baik dalam membaca surat-suratan pendek (Al-Fatihah, Al-Ikhlas,  An-Naas, Al-Falah), mampu membaca doa sehari-hari (doa sebelum makan, sebelum tidur, sebelum wudlu)', '', '', '', '', '', '', '125', '', '21', '', 'baik', 'baik', 'baik', '-', '-', '-', '-', '-', '-', '', '', '', '', '', '', 'Tingkatkan belajarmu !'),
(117, '1103', 'Dyaz Eka Winata', 'kelas 1', 'SD Negeri 2 Glagah', '', 'Logede, Glagah, Temon, Kulon Progo', 'Sangat baik dalam   ketaatan beribadah, perilaku bersyukur, Baik dalam berdoa sebelum dan sesudah melakukan kegiatan, toleransi dalam beribadah, ', 'Baik dalam sikap jujur, disiplin, percaya diri, tanggung jawab, sopan santun, kerja sama, ', 'Pramuka', 'B', 'Sudah mampu dalam membaca syahadat, baik dalam membaca doa sehari-hari, memberi salam pramuka dan mengenal dwi satya dan dwi darma', 'TPA', 'B', 'Sudah baik dalam membaca surat-suratan pendek (Al-Fatihah, Al-Ikhlas,  An-Naas, Al-Falah), mampu membaca doa sehari-hari (doa sebelum makan, sebelum tidur, sebelum wudlu)', '', '', '', '', '', '', '121', '', '22', '', 'baik', 'baik', 'baik', '-', '-', '-', '-', '-', '-', '', '', '', '', '', '', 'Belajarlah yang lebih giat lagi, perbanyak belajar menghitung !'),
(118, '1104', 'Dzaky Athaya Muhammad Salim', 'kelas 1', 'SD Negeri 2 Glagah', '', 'Keboan, Karangwuni, Wates, Kulon Progo', 'Baik dalam ketaatan beribadah, perilaku bersyukur, berdoa sebelum dan sesudah melakukan kegiatan, toleransi dalam beribadah, ', 'Baik dalam sikap jujur, disiplin, percaya diri, tanggung jawab, sopan santun, kerja sama, ', 'Pramuka', 'B', 'Sudah mampu dalam membaca syahadat, baik dalam membaca doa sehari-hari, memberi salam pramuka dan mengenal dwi satya dan dwi darma', 'TPA', 'B', 'Sudah baik dalam membaca surat-suratan pendek (Al-Fatihah, Al-Ikhlas,  An-Naas, Al-Falah), mampu membaca doa sehari-hari (doa sebelum makan, sebelum tidur, sebelum wudlu)', '', '', '', '', '', '', '120', '', '23', '', 'kurang bai', 'baik', 'baik', '-', '-', '-', '-', '-', '-', '', '', '', '', '', '', 'Belajarlah yang lebih giat, tingkatkan kedisiplinan !'),
(119, '1105', 'Haya Hafizhah', 'kelas 1', 'SD Negeri 2 Glagah', '', 'Glagah, Glagah, Temon, Kulon Progo', 'Sangat baik dalam   ketaatan beribadah, perilaku bersyukur, berdoa sebelum dan sesudah melakukan kegiatan, Baik dalam toleransi dalam beribadah, ', 'Sangat  sopan santun, kerja sama, Baik dalam sikap jujur, disiplin, percaya diri, tanggung jawab, ', 'Pramuka', 'B', 'Sudah mampu dalam membaca syahadat, baik dalam membaca doa sehari-hari, memberi salam pramuka dan mengenal dwi satya dan dwi darma', 'TPA', 'B', 'Sudah baik dalam membaca surat-suratan pendek (Al-Fatihah, Al-Ikhlas,  An-Naas, Al-Falah), mampu membaca doa sehari-hari (doa sebelum makan, sebelum tidur, sebelum wudlu)', '', '', '', '', '', '', '115', '', '19', '', 'baik', 'baik', 'baik', '-', '-', '-', '-', '-', '-', '', '', '', '', '', '', 'Belajarlah yang lebih giat lagi !'),
(120, '1106', 'Kevin Aldi Prasetya', 'kelas 1', 'SD Negeri 2 Glagah', '', 'Glagah, Glagah, Temon, Kulon Progo', 'Baik dalam ketaatan beribadah, perilaku bersyukur, berdoa sebelum dan sesudah melakukan kegiatan, toleransi dalam beribadah, ', 'Baik dalam sikap jujur, disiplin, percaya diri, tanggung jawab, sopan santun, kerja sama, ', 'Pramuka', 'B', 'Sudah mampu dalam membaca syahadat, baik dalam membaca doa sehari-hari, memberi salam pramuka dan mengenal dwi satya dan dwi darma', 'TPA', 'B', 'Sudah baik dalam membaca surat-suratan pendek (Al-Fatihah, Al-Ikhlas,  An-Naas, Al-Falah), mampu membaca doa sehari-hari (doa sebelum makan, sebelum tidur, sebelum wudlu)', '', '', '', '', '', '', '113', '', '25', '', 'kurang bai', 'baik', 'baik', '-', '-', '-', '-', '-', '-', '', '', '', '', '', '', 'Tingkatkan belajarmu, perbanyak belajar menulis !'),
(121, '1107', 'Miswa Putri Ramadhani', 'kelas 1', 'SD Negeri 2 Glagah', '', 'Sangkretan, Glagah, Temon, Kulon Progo', 'Sangat baik dalam   ketaatan beribadah, berdoa sebelum dan sesudah melakukan kegiatan, Baik dalam perilaku bersyukur, toleransi dalam beribadah, ', 'Sangat  sopan santun, Baik dalam sikap jujur, disiplin, percaya diri, tanggung jawab, kerja sama, ', 'Pramuka', 'B', 'Sudah mampu dalam membaca syahadat, baik dalam membaca doa sehari-hari, memberi salam pramuka dan mengenal dwi satya dan dwi darma', 'TPA', 'B', 'Sudah baik dalam membaca surat-suratan pendek (Al-Fatihah, Al-Ikhlas,  An-Naas, Al-Falah), mampu membaca doa sehari-hari (doa sebelum makan, sebelum tidur, sebelum wudlu)', '', '', '', '', '', '', '117', '', '19', '', 'baik', 'baik', 'baik', '-', '-', '-', '-', '-', '-', '', '', '', '', '', '', 'Belajarlah yang lebih giat lagi !'),
(122, '1108', 'Muhammad Rafi Aldiansyah', 'kelas 1', 'SD Negeri 2 Glagah', '', 'Bebekan, Glagah, Temon, Kulon Progo', 'Sangat baik dalam   ketaatan beribadah, perilaku bersyukur, berdoa sebelum dan sesudah melakukan kegiatan, Baik dalam toleransi dalam beribadah, ', 'Baik dalam sikap jujur, disiplin, percaya diri, tanggung jawab, sopan santun, kerja sama, ', 'Pramuka', 'B', 'Sudah mampu dalam membaca syahadat, baik dalam membaca doa sehari-hari, memberi salam pramuka dan mengenal dwi satya dan dwi darma', 'TPA', 'B', 'Sudah baik dalam membaca surat-suratan pendek (Al-Fatihah, Al-Ikhlas,  An-Naas, Al-Falah), mampu membaca doa sehari-hari (doa sebelum makan, sebelum tidur, sebelum wudlu)', '', '', '', '', '', '', '120', '', '18', '', 'baik', 'kurang bai', 'baik', '-', '-', '-', '-', '-', '-', '', '', '', '', '', '', 'Belajarlah yang lebih giat lagi !'),
(123, '1109', 'Nabila Ayu Saskia Ningrum', 'kelas 1', 'SD Negeri 2 Glagah', '', 'Bebekan, Glagah, Temon, Kulon Progo', 'Baik dalam ketaatan beribadah, cukup dalam perilaku bersyukur, berdoa sebelum dan sesudah melakukan kegiatan, toleransi dalam beribadah, ', 'Baik dalam sikap jujur, disiplin, percaya diri, tanggung jawab, sopan santun, kerja sama, ', 'Pramuka', 'B', 'Sudah mampu dalam membaca syahadat, baik dalam membaca doa sehari-hari, memberi salam pramuka dan mengenal dwi satya dan dwi darma', 'TPA', 'B', 'Sudah baik dalam membaca surat-suratan pendek (Al-Fatihah, Al-Ikhlas,  An-Naas, Al-Falah), mampu membaca doa sehari-hari (doa sebelum makan, sebelum tidur, sebelum wudlu)', '', '', '', '', '', '', '117', '', '22', '', 'baik', 'baik', 'baik', '-', '-', '-', '-', '-', '-', '', '', '', '', '', '', 'Tingkatkan belajarmu, perbanyak belajar membaca dan menulis !'),
(124, '1110', 'Nabila Septianing Tyas', 'kelas 1', 'SD Negeri 2 Glagah', '', 'Glagah, Glagah, Temon, Kulon Progo', 'Sangat baik dalam   berdoa sebelum dan sesudah melakukan kegiatan, Baik dalam ketaatan beribadah, perilaku bersyukur, toleransi dalam beribadah, ', 'Baik dalam sikap jujur, disiplin, percaya diri, tanggung jawab, sopan santun, kerja sama, ', 'Pramuka', 'B', 'Sudah mampu dalam membaca syahadat, baik dalam membaca doa sehari-hari, memberi salam pramuka dan mengenal dwi satya dan dwi darma', 'TPA', 'B', 'Sudah baik dalam membaca surat-suratan pendek (Al-Fatihah, Al-Ikhlas,  An-Naas, Al-Falah), mampu membaca doa sehari-hari (doa sebelum makan, sebelum tidur, sebelum wudlu)', '', '', '', '', '', '', '138', '', '42', '', 'baik', 'baik', 'baik', '-', '-', '-', '-', '-', '-', '', '', '', '', '', '', 'Belajarlah yang lebih giat lagi !'),
(125, '1111', 'Rakha Boma Nandana', 'kelas 1', 'SD Negeri 2 Glagah', '', 'Glagah, Glagah, Temon, Kulon Progo', 'Sangat baik dalam   ketaatan beribadah, Baik dalam perilaku bersyukur, berdoa sebelum dan sesudah melakukan kegiatan, toleransi dalam beribadah, ', 'Baik dalam sikap jujur, disiplin, percaya diri, tanggung jawab, sopan santun, kerja sama, ', 'Pramuka', 'B', 'Sudah mampu dalam membaca syahadat, baik dalam membaca doa sehari-hari, memberi salam pramuka dan mengenal dwi satya dan dwi darma', 'TPA', 'B', 'Sudah baik dalam membaca surat-suratan pendek (Al-Fatihah, Al-Ikhlas,  An-Naas, Al-Falah), mampu membaca doa sehari-hari (doa sebelum makan, sebelum tidur, sebelum wudlu)', '', '', '', '', '', '', '117', '', '19', '', 'baik', 'baik', 'baik', '-', '-', '-', '-', '-', '-', '', '', '', '', '', '', 'Tingkatkan belajar membaca !'),
(126, '1112', 'Rayyan Khairul Azam', 'kelas 1', 'SD Negeri 2 Glagah', '', 'Sangkretan, Glagah, Temon, Kulon Progo', 'Sangat baik dalam   ketaatan beribadah, perilaku bersyukur, berdoa sebelum dan sesudah melakukan kegiatan, Baik dalam toleransi dalam beribadah, ', 'Baik dalam sikap jujur, disiplin, percaya diri, tanggung jawab, sopan santun, kerja sama, ', 'Pramuka', 'B', 'Sudah mampu dalam membaca syahadat, baik dalam membaca doa sehari-hari, memberi salam pramuka dan mengenal dwi satya dan dwi darma', 'TPA', 'B', 'Sudah baik dalam membaca surat-suratan pendek (Al-Fatihah, Al-Ikhlas,  An-Naas, Al-Falah), mampu membaca doa sehari-hari (doa sebelum makan, sebelum tidur, sebelum wudlu)', '', '', '', '', '', '', '121', '', '27', '', 'baik', 'baik', 'baik', '-', '-', '-', '-', '-', '-', '', '', '', '', '', '', 'Belajarlah yang lebih giat lagi !'),
(127, '1113', 'Regina Astitra Rahmadonna', 'kelas 1', 'SD Negeri 2 Glagah', '', 'Sangkretan, Glagah, Temon, Kulon Progo', 'Sangat baik dalam   ketaatan beribadah, perilaku bersyukur, berdoa sebelum dan sesudah melakukan kegiatan, Baik dalam toleransi dalam beribadah, ', 'Baik dalam sikap jujur, disiplin, percaya diri, tanggung jawab, sopan santun, kerja sama, ', 'Pramuka', 'B', 'Sudah mampu dalam membaca syahadat, baik dalam membaca doa sehari-hari, memberi salam pramuka dan mengenal dwi satya dan dwi darma', 'TPA', 'B', 'Sudah baik dalam membaca surat-suratan pendek (Al-Fatihah, Al-Ikhlas,  An-Naas, Al-Falah), mampu membaca doa sehari-hari (doa sebelum makan, sebelum tidur, sebelum wudlu)', '', '', '', '', '', '', '120', '', '17', '', 'baik', 'baik', 'baik', '-', '-', '-', '-', '-', '-', '', '', '', '', '', '', 'Belajarlah yang lebih giat lagi !'),
(128, '1114', 'Safiq Satriawan', 'kelas 1', 'SD Negeri 2 Glagah', '', 'Glagah, Glagah, Temon, Kulon Progo', 'Baik dalam ketaatan beribadah, perilaku bersyukur, berdoa sebelum dan sesudah melakukan kegiatan, toleransi dalam beribadah, ', 'Baik dalam sikap jujur, disiplin, percaya diri, tanggung jawab, sopan santun, kerja sama, ', 'Pramuka', 'B', 'Sudah mampu dalam membaca syahadat, baik dalam membaca doa sehari-hari, memberi salam pramuka dan mengenal dwi satya dan dwi darma', 'TPA', 'B', 'Sudah baik dalam membaca surat-suratan pendek (Al-Fatihah, Al-Ikhlas,  An-Naas, Al-Falah), mampu membaca doa sehari-hari (doa sebelum makan, sebelum tidur, sebelum wudlu)', '', '', '', '', '', '', '118', '', '15', '', 'baik', 'baik', 'baik', '-', '-', '-', '-', '-', '-', '', '', '', '', '', '', 'Belajarlah yang lebih giat, perbanyak belajar menulis !');

--
-- Indexes for dumped tables
--

--
-- Indeks untuk tabel `rapor_pribadi`
--
ALTER TABLE `rapor_pribadi`
  ADD PRIMARY KEY (`id_rapor`);

--
-- AUTO_INCREMENT untuk tabel yang dibuang
--

--
-- AUTO_INCREMENT untuk tabel `rapor_pribadi`
--
ALTER TABLE `rapor_pribadi`
  MODIFY `id_rapor` int(5) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=129;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
